nelmio_api_doc:
    documentation:
        info:
            title: Pay Buddy
            description: Это проект Pay Buddy на Хакатон команды OurEra soft !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
