services:
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile.prod
    container_name: ${PHP_CONTAINER_NAME}
    env_file: .env
    expose:
      - 9000
    volumes:
      - ../:/app:cached
    environment:
      PHP_IDE_CONFIG: "serverName=docker-server"

  nginx:
    build:
      context: nginx
    container_name: ${NGINX_CONTAINER_NAME}
    env_file: .env
    depends_on:
      - php
    volumes:
      - ../:/app:cached
      - ./letsencrypt:/etc/letsencrypt
      - "./nginx/conf.d.prod:/etc/nginx/conf.d"
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  db:
    build: ./db
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - "${DB_EXTERNAL_DATA}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}


volumes:
  certs:
